#!/bin/sh
#
# rcS		Call all S??* scripts in /etc/rcS.d in
#		numerical/alphabetical order.
#
# Version:	@(#)/etc/init.d/rcS  2.76  19-Apr-1999  miquels@cistron.nl
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

mkdir -p /data
mkdir -p /ssdp0
mkdir -p /ssdp1

hwclock --hctosys --localtime --rtc=/dev/rtc1
insmod /lib/modules/`uname -r`/kernel/drivers/misc/ipc-shm/ipc-shm-dev.ko
insmod /lib/modules/`uname -r`/kernel/drivers/misc/ipc-emcom/ipc-emcom-drv.ko
#	Make sure proc is mounted
#
[ -d "/proc/1" ] || mount /proc

#
#	Source defaults.
#
. /etc/default/rcS

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
trap ":" INT QUIT TSTP

#
#	Call all parts in order.
#
exec /etc/init.d/rc S


